# EDA - Exploratory data analysis
So as an initial step im going to open up the data
and have a look around... (yeah i'll try and fit it also)

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import linear_model
from sklearn import preprocessing

%matplotlib inline

In [94]:
training_data = pd.read_csv('../data/train.csv', index_col=0)
test_data = pd.read_csv('../data/test.csv', index_col=0)

print('samples:', len(training_data))
print('dimensions: ', len(training_data.columns) - 1)

training_data.describe()

samples: 250
dimensions:  300

,target,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,...,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,0.640000,0.023292,-0.026872,0.167404,0.001904,0.001588,-0.007304,0.032052,0.078412,-0.036920,...,0.044652,0.126344,0.018436,-0.012092,-0.065720,-0.106112,0.046472,0.006452,0.009372,-0.128952
std,0.480963,0.998354,1.009314,1.021709,1.011751,1.035411,0.955700,1.006657,0.939731,0.963688,...,1.011416,0.972567,0.954229,0.960630,1.057414,1.038389,0.967661,0.998984,1.008099,0.971219
min,0.000000,-2.319000,-2.931000,-2.477000,-2.359000,-2.566000,-2.845000,-2.976000,-3.444000,-2.768000,...,-2.804000,-2.443000,-2.757000,-2.466000,-3.287000,-3.072000,-2.634000,-2.776000,-3.211000,-3.500000
25%,0.000000,-0.644750,-0.739750,-0.425250,-0.686500,-0.659000,-0.643750,-0.675000,-0.550750,-0.689500,...,-0.617000,-0.510500,-0.535750,-0.657000,-0.818500,-0.821000,-0.605500,-0.751250,-0.550000,-0.754250
50%,1.000000,-0.015500,0.057000,0.184000,-0.016500,-0.023000,0.037500,0.060500,0.183500,-0.012500,...,0.067500,0.091000,0.057500,-0.021000,-0.009000,-0.079500,0.009500,0.005500,-0.009000,-0.132500
75%,1.000000,0.677000,0.620750,0.805000,0.720000,0.735000,0.660500,0.783250,0.766250,0.635000,...,0.797250,0.804250,0.631500,0.650250,0.739500,0.493000,0.683000,0.794250,0.654250,0.503250
max,1.000000,2.567000,2.419000,3.392000,2.771000,2.901000,2.793000,2.546000,2.846000,2.512000,...,2.865000,2.801000,2.736000,2.596000,2.226000,3.131000,3.236000,2.626000,3.530000,2.771000

more dimensions than samples.. 
300 dimensions... maybe too many for a histogram table, messy trying to describe!

In [95]:
Y_train = training_data.loc[:, 'target'].values
X_train = training_data.drop('target', axis=1).values

X_scaled = preprocessing.scale(X_train)
Y_train = Y_train.ravel()

In [96]:
X_test = test_data.values
X_test = preprocessing.scale(X_test)

In [97]:
model = linear_model.LogisticRegression(solver='lbfgs')
model.fit(X_scaled, Y_train)

output = pd.Series(index=test_data.index, data=model.predict(X_test), name='target')
output.to_csv('../results/log_submission.csv', header='id')
print(len(output))

19750